---
fail_fast: false
minimum_pre_commit_version: "2.6.0"
repos:
  -
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: double-quote-string-fixer
  -
    repo: https://github.com/aws-ia/pre-commit-hooks
    rev: v1.0
    hooks: []
  #     - id: aws-ia-meta-hook
